---
volume_backup_stats_state: "{{ 'present' if volume_backup_stats_root is truthy else 'absent' }}"
volume_backup_stats_metric_name: volume_backups
volume_backup_stats_root: "{{ docker_volume_backup_root|default('', true) }}"
volume_backup_stats_archive_glob: backup-*.tar.gz
volume_backup_stats_interval_s: 300
