- assert:
    that: telegraf_state in ('present', 'absent')
    quiet: yes

- include_tasks: present.yml
  when: telegraf_state == 'present'

- include_tasks: absent.yml
  when: telegraf_state == 'absent'

- meta: flush_handlers
