#!/usr/bin/env python3
import json
import subprocess
import sys
import traceback

if __name__ == '__main__':
    stats = [
        'accounting.buffer_size',
        'accounting.mode',
        'clocks.applications.graphics',
        'clocks.applications.memory',
        'clocks.current.graphics',
        'clocks.current.memory',
        'clocks.current.sm',
        'clocks.current.video',
        'clocks.default_applications.graphics',
        'clocks.default_applications.memory',
        'clocks.max.graphics',
        'clocks.max.memory',
        'clocks.max.sm',
        'clocks_throttle_reasons.active',
        'clocks_throttle_reasons.applications_clocks_setting',
        'clocks_throttle_reasons.gpu_idle',
        'clocks_throttle_reasons.hw_power_brake_slowdown',
        'clocks_throttle_reasons.hw_slowdown',
        'clocks_throttle_reasons.hw_thermal_slowdown',
        'clocks_throttle_reasons.supported',
        'clocks_throttle_reasons.sw_power_cap',
        'clocks_throttle_reasons.sw_thermal_slowdown',
        'clocks_throttle_reasons.sync_boost',
        'compute_mode',
        'count',
        'display_active',
        'display_mode',
        'driver_model.current',
        'driver_model.pending',
        'driver_version',
        'ecc.errors.corrected.aggregate.cbu',
        'ecc.errors.corrected.aggregate.device_memory',
        'ecc.errors.corrected.aggregate.dram',
        'ecc.errors.corrected.aggregate.l1_cache',
        'ecc.errors.corrected.aggregate.l2_cache',
        'ecc.errors.corrected.aggregate.register_file',
        'ecc.errors.corrected.aggregate.sram',
        'ecc.errors.corrected.aggregate.texture_memory',
        'ecc.errors.corrected.aggregate.total',
        'ecc.errors.corrected.volatile.cbu',
        'ecc.errors.corrected.volatile.device_memory',
        'ecc.errors.corrected.volatile.dram',
        'ecc.errors.corrected.volatile.l1_cache',
        'ecc.errors.corrected.volatile.l2_cache',
        'ecc.errors.corrected.volatile.register_file',
        'ecc.errors.corrected.volatile.sram',
        'ecc.errors.corrected.volatile.texture_memory',
        'ecc.errors.corrected.volatile.total',
        'ecc.errors.uncorrected.aggregate.cbu',
        'ecc.errors.uncorrected.aggregate.device_memory',
        'ecc.errors.uncorrected.aggregate.dram',
        'ecc.errors.uncorrected.aggregate.l1_cache',
        'ecc.errors.uncorrected.aggregate.l2_cache',
        'ecc.errors.uncorrected.aggregate.register_file',
        'ecc.errors.uncorrected.aggregate.sram',
        'ecc.errors.uncorrected.aggregate.texture_memory',
        'ecc.errors.uncorrected.aggregate.total',
        'ecc.errors.uncorrected.volatile.cbu',
        'ecc.errors.uncorrected.volatile.device_memory',
        'ecc.errors.uncorrected.volatile.dram',
        'ecc.errors.uncorrected.volatile.l1_cache',
        'ecc.errors.uncorrected.volatile.l2_cache',
        'ecc.errors.uncorrected.volatile.register_file',
        'ecc.errors.uncorrected.volatile.sram',
        'ecc.errors.uncorrected.volatile.texture_memory',
        'ecc.errors.uncorrected.volatile.total',
        'ecc.mode.current',
        'ecc.mode.pending',
        'encoder.stats.averageFps',
        'encoder.stats.averageLatency',
        'encoder.stats.sessionCount',
        'enforced.power.limit',
        'fan.speed',
        'gpu_operation_mode.current',
        'gpu_operation_mode.pending',
        'index',
        'inforom.ecc',
        'inforom.img',
        'inforom.oem',
        'inforom.pwr',
        'memory.free',
        'memory.total',
        'memory.used',
        'mig.mode.current',
        'mig.mode.pending',
        'name',
        'pci.bus',
        'pci.bus_id',
        'pci.device',
        'pci.device_id',
        'pci.domain',
        'pci.sub_device_id',
        'pcie.link.gen.current',
        'pcie.link.gen.max',
        'pcie.link.width.current',
        'pcie.link.width.max',
        'persistence_mode',
        'power.default_limit',
        'power.draw',
        'power.limit',
        'power.management',
        'power.max_limit',
        'power.min_limit',
        'pstate',
        'retired_pages.double_bit.count',
        'retired_pages.pending',
        'retired_pages.single_bit_ecc.count',
        'serial',
        'temperature.gpu',
        'temperature.memory',
        'utilization.gpu',
        'utilization.memory',
        'uuid',
        'vbios_version',
    ]

    # noinspection PyBroadException
    try:
        output = subprocess.check_output(
            [
                'nvidia-smi',
                '--format=noheader,nounits,csv',
                '--query-gpu={}'.format(','.join(stats))
            ],
            stderr=subprocess.STDOUT
        )
        all_gpu_stats = []
        for line in output.splitlines(False):
            values = [x.strip() for x in line.split(b',')]
            gpu_stats = {}
            for name, value in zip(stats, [x.strip() for x in line.split(b',')]):
                # noinspection PyBroadException
                try:
                    gpu_stats[name] = float(value)
                except:
                    pass
            all_gpu_stats.append(gpu_stats)
        json.dump(all_gpu_stats, sys.stdout)
        sys.exit(0)
    except Exception as e:
        traceback.print_exc(file=sys.stderr)
        sys.exit(1)
