- name: additional authorized ssh keys
  authorized_key:
    user: "{{ item.user }}"
    key: "{{ item.key }}"
    state: "{{ item.state|default('present') }}"
  with_items: "{{ authorized_keys }}"

- name: additional sudoers
  template:
    src: sudoers.d/ansible-managed.jinja2
    dest: /etc/sudoers.d/ansible-managed
    owner: root
    group: root
    mode: 0440
    validate: 'visudo -cf %s'
  when: sudoers|default([])|length > 0

- name: delete additional sudoers file
  file:
    path: /etc/sudoers.d/ansible-managed
    state: absent
  when: sudoers|default([])|length == 0

- name: update time zone database
  apt:
    name: tzdata
    state: latest
  notify: restart cron

- name: set time zone
  timezone:
    name: "{{ timezone }}"
  notify: restart cron
  when: timezone != ''

- name: update apt cache
  apt:
    update_cache: yes
  register: result
  until: result is succeeded
  changed_when: False

- name: install common packages
  apt:
    name: "{{ common_pkgs.apt }}"
    state: latest

- meta: flush_handlers
