#!/usr/bin/env bash
#
# Query NUT UPS status and output in InfluxDB Line Protocol
#
# Usage: ups-stats upsname[@hostname[:port]]
# (same as `upsc`, see https://networkupstools.org/docs/man/upsc.html)

set -euo pipefail
IFS=$'\n\t'

function join() {
  local IFS="$1"
  shift
  echo "$*"
}

declare -A vars

# read UPS status into `vars`
while IFS=": " read -r k v; do
  vars[$k]="$v"
done < <(upsc "$*" 2>/dev/null)

# exit if empty/unsuccessful
[[ -z "${vars-}" ]] || exit 1

# print a metric in InfluxDB line format
tags=( "ups=${1%%@*}" )
[[ -n "${vars["ups.mfr"]+_}" ]] && tags+=("manufacturer=${vars["ups.mfr"]// /\\ }")
[[ -n "${vars["ups.model"]+_}" ]] && tags+=("model=${vars["ups.model"]// /\\ }")
[[ -n "${vars["ups.productid"]+_}" ]] && tags+=("product_id=${vars["ups.productid"]// /\\ }")
[[ -n "${vars["ups.vendorid"]+_}" ]] && tags+=("vendor_id=${vars["ups.vendorid"]// /\\ :-\\"\\"}")
[[ -n "${vars["battery.type"]+_}" ]] && tags+=("battery_type=${vars["battery.type"]// /\\ :-\\"\\"}")

fields=()
[[ -n "${vars["ups.status"]+_}" ]] && fields+=("status=\"${vars["ups.status"]}\"")
[[ -n "${vars["battery.charge"]+_}" ]] && fields+=("battery_charge=${vars["battery.charge"]}")
[[ -n "${vars["battery.charge.low"]+_}" ]] && fields+=("battery_charge_low=${vars["battery.charge.low"]}")
[[ -n "${vars["battery.charge.warning"]+_}" ]] && fields+=("battery_charge_warning=${vars["battery.charge.warning"]}")
[[ -n "${vars["battery.runtime"]+_}" ]] && fields+=("battery_runtime=${vars["battery.runtime"]}")
[[ -n "${vars["battery.runtime.low"]+_}" ]] && fields+=("battery_runtime_low=${vars["battery.runtime.low"]}")
[[ -n "${vars["battery.voltage"]+_}" ]] && fields+=("battery_voltage=${vars["battery.voltage"]}")
[[ -n "${vars["battery.voltage.nominal"]+_}" ]] && fields+=("battery_voltage_nominal=${vars["battery.voltage.nominal"]}")
[[ -n "${vars["ups.beeper.status"]+_}" ]] && fields+=("beeper_status=\"${vars["ups.beeper.status"]}\"")
[[ -n "${vars["ups.delay.shutdown"]+_}" ]] && fields+=("delay_shutdown=${vars["ups.delay.shutdown"]}")
[[ -n "${vars["ups.delay.start"]+_}" ]] && fields+=("delay_start=${vars["ups.delay.start"]}")
[[ -n "${vars["input.voltage"]+_}" ]] && fields+=("input_voltage=${vars["input.voltage"]}")
[[ -n "${vars["input.voltage.nominal"]+_}" ]] && fields+=("input_voltage_nominal=${vars["input.voltage.nominal"]}")
[[ -n "${vars["ups.load"]+_}" ]] && fields+=("load=${vars["ups.load"]}")
[[ -n "${vars["output.voltage"]+_}" ]] && fields+=("output_voltage=${vars["output.voltage"]}")
[[ -n "${vars["ups.realpower.nominal"]+_}" ]] && fields+=("realpower_nominal=${vars["ups.realpower.nominal"]}")
[[ -n "${vars["ups.serial"]+_}" ]] && fields+=("serial_number=\"${vars["ups.serial"]}\"")
[[ -n "${vars["ups.timer.shutdown"]+_}" ]] && fields+=("timer_shutdown=${vars["ups.timer.shutdown"]}")
[[ -n "${vars["ups.timer.start"]+_}" ]] && fields+=("timer_start=${vars["ups.timer.start"]}")
[[ -n "${vars["input.transfer.low"]+_}" ]] && fields+=("input_transfer_low=${vars["input.transfer.low"]}")
[[ -n "${vars["input.transfer.high"]+_}" ]] && fields+=("input_transfer_high=${vars["input.transfer.high"]}")
[[ -n "${vars["driver.name"]+_}" ]] && fields+=("driver_name=\"${vars["driver.name"]}\"")
[[ -n "${vars["driver.version"]+_}" ]] && fields+=("driver_version=\"${vars["driver.version"]}\"")

time=$(date +%s%N)
echo "ups,$(join , "${tags[@]}") $(join , "${fields[@]}") $time"
